blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Questions and Help | ğŸ’¬ Chat With Us
    url: https://discord.com/invite/5caWS7R6QX
    about: Please ask and answer questions here.
  - name: ğŸ™‹ Have a question to discuss?
    url: https://github.com/testsigmahq/testsigma/discussions
    about: Start a GitHub discussion
  - name: â˜ï¸ Dedicated Help & Support Center | Testsigma Cloud
    url: https://app.testsigma.com/ui/support
    about: Dedicated suport for issues related to Testsigma Cloud âš¡ï¸
  - name: ğŸ“ƒ Documentation/Tutorials Issues & Enhancements
    url: https://github.com/testsigmahq/testsigma/issues/new
    about: Please open documentation issues here.
